<?php
/**
 * @file
 * Code for the Linkedin_user feature.
 */

include_once 'linkedin_user.features.inc';
 function linkedin_user_form_user_login_block_alter(&$form, &$form_state, $form_id) {
     $form['name']['#attributes']['placeholder']  = 'Email';
     $form['name']['#title_display']  = 'invisible';
     $form['pass']['#attributes']['placeholder'] = 'Password';
     $form['pass']['#title_display'] = 'invisible';
     $form['actions']['submit']['#value'] = t('Sign In');
     $markup = l(t('Forgot password?'), 'user/password');
     $markup = '<div class="clearfix">' . $markup . '</div>';
     $form['links']['#markup'] = $markup;
     $form['links']['#weight'] = 100;
     }

 /**
  * Implements hook_form_alter().
  */
 function linkedin_user_form_alter(&$form, &$form_state, $form_id) {
 if($form_id == 'user_register_form') {
   $form['password'] = array(
     '#type' => 'password',
     '#title' => t('Password(6 or more characters)'),
     '#size'  => 30,
     '#maxlength' => 32,
     '#required' => TRUE,
     '#weight' => 3,
     );

     $form['mail']['#size'] =30;
     $form['actions']['submit']['#value'] = t('Join now');
     $form['cutomtext'] = array(
     '#type' => 'item',
     '#markup' => '<div id="textcustom" ><label id="customise">By clicking Join now, you agree to the LinkedIn <a href="#" id="policylink">User Agreement</a>,<a href="#" id="policylink"> Privacy Policy</a>, and <a href="#" id="policylink">Cookie Policy</a>.</label></div>',
     '#weight' => 4, // Adjust so that you can place it whereever
     );
   }
 }
